name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories \
            --repository-names ${{ secrets.ECR_REPO_NAME }} \
            --region us-east-1 || \
          aws ecr create-repository \
            --repository-name ${{ secrets.ECR_REPO_NAME }} \
            --region us-east-1

      - name: Build Docker image
        run: |
          docker build --platform linux/amd64 -t ${{ secrets.ECR_REPO_NAME }} ./backend

      - name: Tag and Push Image
        run: |
          ECR_URL=$(aws ecr describe-repositories \
            --repository-names ${{ secrets.ECR_REPO_NAME }} \
            --region us-east-1 \
            --query "repositories[0].repositoryUri" \
            --output text)

          docker tag ${{ secrets.ECR_REPO_NAME }}:latest $ECR_URL:latest
          docker push $ECR_URL:latest

          echo "ECR_URL=$ECR_URL" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra/envs/dev
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/envs/dev
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: infra/envs/dev
        run: terraform apply -auto-approve tfplan
